site_name: reviewer
site_description: A simple API that allows users to post and retrieve their reviews.
repo_url: https://github.com/antoniostorni/reviewer
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/antoniostorni">antoniostorni</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
